export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: 'operators.contains', value: 'iLike' as const },
    { label: 'operators.doesNotContain', value: 'notILike' as const },
    { label: 'operators.is', value: 'eq' as const },
    { label: 'operators.isNot', value: 'ne' as const },
    { label: 'operators.isEmpty', value: 'isEmpty' as const },
    { label: 'operators.isNotEmpty', value: 'isNotEmpty' as const },
  ],
  numericOperators: [
    { label: 'operators.is', value: 'eq' as const },
    { label: 'operators.isNot', value: 'ne' as const },
    { label: 'operators.isLessThan', value: 'lt' as const },
    { label: 'operators.isLessThanOrEqualTo', value: 'lte' as const },
    { label: 'operators.isGreaterThan', value: 'gt' as const },
    { label: 'operators.isGreaterThanOrEqualTo', value: 'gte' as const },
    { label: 'operators.isBetween', value: 'isBetween' as const },
    { label: 'operators.isEmpty', value: 'isEmpty' as const },
    { label: 'operators.isNotEmpty', value: 'isNotEmpty' as const },
  ],
  dateOperators: [
    { label: 'operators.is', value: 'eq' as const },
    { label: 'operators.isNot', value: 'ne' as const },
    { label: 'operators.isBefore', value: 'lt' as const },
    { label: 'operators.isAfter', value: 'gt' as const },
    { label: 'operators.isOnOrBefore', value: 'lte' as const },
    { label: 'operators.isOnOrAfter', value: 'gte' as const },
    { label: 'operators.isBetween', value: 'isBetween' as const },
    { label: 'operators.isRelativeToToday', value: 'isRelativeToToday' as const },
    { label: 'operators.isEmpty', value: 'isEmpty' as const },
    { label: 'operators.isNotEmpty', value: 'isNotEmpty' as const },
  ],
  selectOperators: [
    { label: 'operators.is', value: 'eq' as const },
    { label: 'operators.isNot', value: 'ne' as const },
    { label: 'operators.isEmpty', value: 'isEmpty' as const },
    { label: 'operators.isNotEmpty', value: 'isNotEmpty' as const },
  ],
  multiSelectOperators: [
    { label: 'operators.hasAnyOf', value: 'inArray' as const },
    { label: 'operators.hasNoneOf', value: 'notInArray' as const },
    { label: 'operators.isEmpty', value: 'isEmpty' as const },
    { label: 'operators.isNotEmpty', value: 'isNotEmpty' as const },
  ],
  booleanOperators: [
    { label: 'operators.is', value: 'eq' as const },
    { label: 'operators.isNot', value: 'ne' as const },
  ],
  sortOrders: [
    { label: 'sort.asc', value: 'asc' as const },
    { label: 'sort.desc', value: 'desc' as const },
  ],
  filterVariants: [
    'text',
    'number',
    'range',
    'date',
    'dateRange',
    'boolean',
    'select',
    'multiSelect',
  ] as const,
  operators: [
    'iLike',
    'notILike',
    'eq',
    'ne',
    'inArray',
    'notInArray',
    'isEmpty',
    'isNotEmpty',
    'lt',
    'lte',
    'gt',
    'gte',
    'isBetween',
    'isRelativeToToday',
  ] as const,
  joinOperators: ['and', 'or'] as const,
};
